# Generated by Django 6.0.5 on 2026-05-18 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_has_photos_booking_photos_approved_workphoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], help_text='Rating score from 1 to 5 stars')),
                ('comment', models.TextField(blank=True, help_text='Optional review comment feedback', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time this review was submitted')),
                ('booking', models.OneToOneField(help_text='The completed booking this review is for', on_delete=django.db.models.deletion.CASCADE, related_name='worker_review', to='bookings.booking')),
                ('customer', models.ForeignKey(help_text='The customer who wrote the review', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(help_text='The service provider worker being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
