# Generated by Django 6.0.5 on 2026-05-16 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0002_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='core.area'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='service_areas',
            field=models.ManyToManyField(blank=True, related_name='providers', to='core.area'),
        ),
    ]
